-- ============================================================================
-- workspace-app (Work4Fun) — Recriação do schema Supabase
-- Reconstruído a partir do código-fonte (api/, public/scripts/, lib/supabase.js),
-- já que o projeto original foi deletado por inatividade.
--
-- Rode este script inteiro no SQL Editor do NOVO projeto Supabase.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. PROFILES
-- Ligada 1:1 com auth.users (id = auth.users.id). Criada/atualizada manualmente
-- pelo endpoint /api/users/user_login/profile_update (upsert), não por trigger.
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
    id            uuid primary key references auth.users (id) on delete cascade,
    full_name     text,
    location      text,
    phone         text,
    is_owner      boolean not null default false,
    is_coworker   boolean not null default true,
    avatar_url    text,
    created_at    timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2. WORKSPACES
-- Espaços de coworking cadastrados pelos owners.
-- ----------------------------------------------------------------------------
create table if not exists public.workspaces (
    id                      bigint generated by default as identity primary key,
    user_id                 uuid references public.profiles (id) on delete cascade,
    title                   text not null,
    details                 text,
    price                   numeric(10,2) not null,
    address                 text not null,
    neighborhood            text,
    seats                   integer not null,
    type                    text not null check (type in ('meeting_room', 'private_office', 'open_desk')),
    lease_time              text not null check (lease_time in ('day', 'week', 'month')),
    latitude                double precision,
    longitude               double precision,
    available_from          date,
    amn_kitchen             boolean not null default false,
    amn_parking             boolean not null default false,
    amn_public_transport    boolean not null default false,
    amn_wifi                boolean not null default false,
    amn_printer             boolean not null default false,
    amn_air                 boolean not null default false,
    amn_smoking             boolean not null default false,
    active                  boolean not null default true,
    image_01                text,
    image_02                text,
    image_03                text,
    image_04                text,
    rating                  numeric(2,1) default 0,
    created_at              timestamptz not null default now()
);

create index if not exists workspaces_user_id_idx on public.workspaces (user_id);
create index if not exists workspaces_active_idx on public.workspaces (active);
create index if not exists workspaces_neighborhood_idx on public.workspaces (neighborhood);

-- ----------------------------------------------------------------------------
-- 3. RESERVATIONS
-- Reservas feitas pelos coworkers em cima de um workspace.
-- ----------------------------------------------------------------------------
create table if not exists public.reservations (
    id              bigint generated by default as identity primary key,
    user_id         uuid references public.profiles (id) on delete cascade,
    workspace_id    bigint references public.workspaces (id) on delete cascade,
    start_time      date not null,
    end_time        date not null,
    lease_time      text,
    rent_price      numeric(10,2),
    rent_total      numeric(10,2),
    status          text default 'pending',
    payment_status  text default 'pending',
    created_at      timestamptz not null default now()
);

create index if not exists reservations_user_id_idx on public.reservations (user_id);
create index if not exists reservations_workspace_id_idx on public.reservations (workspace_id);

-- ============================================================================
-- 4. ROW LEVEL SECURITY
--
-- IMPORTANTE: o back-end (lib/supabase.js) conecta usando a chave "anon"
-- (SUPABASE_KEY), sem propagar o JWT do usuário nas chamadas .from(...).
-- Ou seja, no projeto original, o RLS precisava permitir acesso via role
-- "anon" para as rotas funcionarem (leitura pública de workspaces, inserts
-- de reservas/perfis feitos pelo próprio backend, etc).
--
-- As policies abaixo replicam esse comportamento (permissivo) para o app
-- funcionar exatamente como antes. Ver ressalva de segurança no final.
-- ============================================================================

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.reservations enable row level security;

-- PROFILES: leitura e escrita liberadas para anon/authenticated (o backend
-- filtra por id manualmente em cada rota).
create policy "profiles_select_all" on public.profiles
    for select using (true);

create policy "profiles_insert_all" on public.profiles
    for insert with check (true);

create policy "profiles_update_all" on public.profiles
    for update using (true) with check (true);

-- WORKSPACES: leitura pública; escrita liberada (o backend valida user_id
-- na aplicação, não via RLS).
create policy "workspaces_select_all" on public.workspaces
    for select using (true);

create policy "workspaces_insert_all" on public.workspaces
    for insert with check (true);

create policy "workspaces_update_all" on public.workspaces
    for update using (true) with check (true);

create policy "workspaces_delete_all" on public.workspaces
    for delete using (true);

-- RESERVATIONS: leitura e escrita liberadas (usadas para calendário de
-- disponibilidade, que precisa ser lido por qualquer visitante).
create policy "reservations_select_all" on public.reservations
    for select using (true);

create policy "reservations_insert_all" on public.reservations
    for insert with check (true);

-- Necessária mesmo sem uma rota de "excluir reserva" no app: quando um
-- workspace é deletado, o ON DELETE CASCADE em reservations.workspace_id
-- também é regido por RLS, então sem essa policy a exclusão do workspace
-- falha se ele tiver reservas associadas.
create policy "reservations_delete_all" on public.reservations
    for delete using (true);

-- ============================================================================
-- 5. STORAGE — bucket "workspaces" (público)
-- Usado para: spaces/{space_id}_{image_code}.jpg e avatars/{user_id}.jpg
-- ============================================================================

insert into storage.buckets (id, name, public)
values ('workspaces', 'workspaces', true)
on conflict (id) do update set public = true;

create policy "workspaces_bucket_public_read"
    on storage.objects for select
    using (bucket_id = 'workspaces');

create policy "workspaces_bucket_public_write"
    on storage.objects for insert
    with check (bucket_id = 'workspaces');

create policy "workspaces_bucket_public_update"
    on storage.objects for update
    using (bucket_id = 'workspaces');

-- ============================================================================
-- FIM DO SCRIPT
-- ============================================================================
